### ISSUE TITLE
Can only build for Python2 or Python3, but not both

### ISSUE THREAD

**Issue by filmil** [Openwsman/openwsman#180]
Trying to follow the build instructions for Linux at https://github.com/Openwsman/openwsman/wiki/installation-of-openwsman-from-source#building-from-source
yields the following

```
╰─>$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ..
-- Version 2.7.2
-- Package Version "2.7"
-- Plugin API Version "2.2"
-- Building for x86_64
-- Libraries will be installed in /home/fmil/local/lib64
-- Configuration will be installed in /home/fmil/local/etc/openwsman
CMake Error at CMakeLists.txt:119 (MESSAGE):
  Can only build for Python2 or Python3, but not both


-- Configuring incomplete, errors occurred!
See also "/home/fmil/tmp/openwsman/build/CMakeFiles/CMakeOutput.log".
```

Thought you might want to know.

**Comment by kkaempf** [comment]
Thanks for the reports, I'll update the docs.

I guess this happens because you have installed (the development files of) Python 2 and Python 3 in parallel.

CMake tries to make an "educated guess" which Python version to compile against by probing its environment.

You can explicitly select the Python version by adding (reverse the booleans for Python 2)
```
  -DBUILD_PYTHON=FALSE  -DBUILD_PYTHON3=TRUE
```
to the CMake call.
